# Generated by Django 3.2.7 on 2021-10-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211016_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propic',
            field=models.ImageField(default='avater.svg', null=True, upload_to=''),
        ),
    ]
