# Generated by Django 3.2.7 on 2021-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
